### ISSUE TITLE
Avoid patching Nix

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#129]
Currently we patch Nix to disable negative narinfo lookups, we should look how to avoid that.

**Comment by dtzWill** [comment]
To disable caching of negative narinfo lookups, you can use
`--option narinfo-cache-negative-ttl 0` -- which might be
close to what you're looking for?

**Comment by roberth** [comment]
Thanks @dtzWill!
We're aware of the option, and also the in-memory `pathInfoCache`, both of which seem problematic. Possibly we've set the option at the wrong time. The `pathInfoCache` is problematic because we can't seem to get the right `Store` object instances to clear it, seemingly defying the C++ spec.

**Comment by domenkozar** [comment]
Could it be that it's a type issue? https://github.com/hercules-ci/hercules-ci-agent/blob/master/hercules-ci-agent/hercules-ci-agent-worker/CNix.hs#L91 hints that it's setting a string, while the value should be an integer.
