### ISSUE TITLE
Multiple keyfiles in the nix module

### ISSUE THREAD

**Issue by mkg20001** [hercules-ci/hercules-ci-agent#190]
Currently I can only use one cluster join token

```
    deployment.keys."cluster-join-token.key".keyFile = ./cluster-join-token.key;
```

It would be great if I could specify multiple tokens.

**Comment by roberth** [comment]
The flake now offers a new module for running multiple agent processes on the same system.

It does not include help with key deployment via NixOps because this feature did not perform a particularly difficult task, but did confuse and obstruct some users.

Instead you can copy the files into the appropriate secrets directories using any means.

Detailed documentation is still forthcoming, but you can give it a try based on the short description in the change log: https://github.com/hercules-ci/hercules-ci-agent/blob/master/hercules-ci-agent/CHANGELOG.md#085
