### ISSUE TITLE
flake ignores nix.package

### ISSUE THREAD

**Issue by nrdxp** [hercules-ci/hercules-ci-agent#268]
When using this repo as a flake input for a flake based NixOS system and importing the `agent-profile` module, even if nix.package is set elsewhere in the NixOS configuration, the flake module seems to ignore it and use the default value for `nix.package` instead. I've tried using mkForce, mkDefault and mkBefore to no effect.

**Comment by roberth** [comment]
Unless you're using `patchNix` to fix up an old version of Nix <2.3.10, the module does not set `nix.package`.
NixOS options are still in a single namespace, even with flakes, so I assume that this is about the agent's evaluator?

The agent evaluator is not based on `nixUnstable` for good reason (if that's what you're trying to accomplish), because not only is it a moving target to compile against, it also has too many issues with crashes and non-deterministic errors. I will continue to contribute fixes in the nix repo to help make Nix 3.0 a realistic option, but as of today it just isn't.

**Comment by Mic92** [comment]
Does hercules works with flake-compat so?

**Comment by roberth** [comment]
@Mic92 Yes, it works with flake-compat. Here's `hercules-ci-agent`'s `nix/ci.nix`:

https://github.com/hercules-ci/hercules-ci-agent/blob/f62ce85aed4c4a7fca9e5da2b00340bbcdc92f88/nix/ci.nix#L1

It uses a custom flake attribute `ciChecks` instead of the official `checks` to take advantage of nix-build-like `recurseIntoAttrs` traversal. It's kind of retrofitted rather than an idiomatic flake, but it gets the job done. In your own `ci.nix`, you could traverse the official flake attributes instead of relying on a single attribute.

**Comment by roberth** [comment]
You could use https://github.com/hercules-ci/flake-compat-ci
It is a stop-gap solution for flakes CI with stable Nix 2.3 and stable Hercules CI.
