### ISSUE TITLE
pin nixpkgs and provide cachix for quicker setup

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#32]
This should spare a couple of minutes for setting up and agent.

**Comment by roberth** [comment]
This makes upstreaming into nixpkgs a lower priority, so we may merge the for-upstream directory into the other files.

**Comment by roberth** [comment]
Ideally we'd use the same nix version as the system, but pinning makes that non-obvious. The agent is already set up to build for multiple for multiple NixOS releases, but we'll need to detect in `module.nix` (or other entrypoints) which pin is appropriate to use. If that's not feasible, the user will have to pick the module version themselves, but that's error prone. Another approach is to require that the user uses our NixOS pin for their deployment, but that's also non-trivial because NixOps uses NIX_PATH.
