### ISSUE TITLE
Don't log full response body on errors

### ISSUE THREAD

**Issue by flokli** [hercules-ci/hercules-ci-agent#49]
Peeking through the logs of `hercules-ci-agent.service`, it seems I did run into some "Bad Gateway" (502) and "Origin SSL Handshake Error" (525) errors.

When these happen, the full `FailureResponse` is logged, including `responseHeaders` and `responseBody`, which can get quite spammy (and probably expose secrets)

I guess it'd be safe to not show these fields, only `statusCode` and `statusMessage (at least in 5xx situations, I'd assume there's a more domain-specific error returned to the client in 4xx situations).

It might be a good idea to print `CF-RAY` from `responseHeaders` when it exists, to help identifying requests on the backend side.

**Comment by roberth** [comment]
Thanks for reporting.
These errors are currently to be expected during backend updates and are harmless. The error bodies are kept to a minimum for this reason, so there should be no real security issue, although we may consider this as a defense-in-depth measure. Typically, requests are sensitive and those aren't logged.
I've added #50 as a measure to decrease 'spamminess'.

**Comment by roberth** [comment]
Re offline conversation:

Perhaps my response to this issue was a bit terse and I should have asked for confirmation.
We try to keep the issue tracker focused and I'm sorry that closing this issue gave the impression that we don't like your solution.
It is a good solution, but it doesn't solve a current issue, which is why, as a maintainer I believe it is better when attention is paid to other issues instead. I do recognize that your suggested approach is an improvement, so I'd be happy to review a solution, as part of this code base or a supporting library like `servant-client`.

It's unfortunate how GitHub renders issue closure, with a :no_entry_sign:. We do appreciate :heart:  your input.
