### ISSUE TITLE
Use a single netrc file

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#72]
Currently netrc is deployed at the global location at `/etc/nix/daemon-netrc` and also provisioned on the fly in a temporary directory and passed when invoking the Nix locally.

Ideally we'd pass netrc only to the client as otherwise global netrc would need to be world readable for client to read it.

However only passing it to the client doesn't work as netrc is actually not used:

```
warning: 'https://xxxx.cachix.org' does not appear to be a binary cache
```

Resolving this issue will gravely simplify agent deployments.

- [ ] Fix the problem
- [ ] Update docs.hercules-ci.com
  - [ ] deployment guide: manual deployment
  - [ ] configuration file docs: binaryCachesPath

**Comment by roberth** [comment]
I expect that we have to change Nix to achieve this. Untrusted users messing with netrc is a DoS risk (through a global narinfo fetching cache), so the daemon shouldn't just accept the netrc. Some ideas:

1. Extend nix-daemon with some sort of limited trust, so that it can accept netrc file paths or content
2. Modify Nix clients to fetch narinfos through the daemon, so the clients do not need access to the netrc file
3. Make nix-daemon ignore any and all cached information about caches when an alternative netrc file is passed

(1) is quite complicated and gives a security 'model' that is too low-level
(2) doesn't let us limit cache access by other users on the agent system but it does guard access to the credentials themselves.
(3) best candidate?

**Comment by domenkozar** [comment]
I'd prefer to implement (2) to hide credentials, but advise against using the OS for anything else but running an agent. We can spend a lot of time on multi-user security and it won't ever be perfect so it's just threading water.

**Comment by roberth** [comment]
Multi-user security will be relevant when we start doing third party PRs for open source, but that's rather long-term anyway. When doing user isolation for tasks, (2) is easier to build on, so you're probably right that (2) is a better choice.

**Comment by domenkozar** [comment]
Eelco said ` it's already the daemon that fetches the nars/narinfos`, so seems like (2) should be achievable if we debug why it didn't work.
